Develop-Sprint 12 Homework - Первая версия
DusynHub/java-filmorate pull request #26
Opened 2023-03-23 20:02 UTC by DusynHub

Реализованы все предолженные в задании задачи.

2023-03-24 16:05 UTC, AnastasiyaFomkina requested changes
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Молодцы, что сделали все задания. Это очень круто 💪 Вы хорошо разобрались во взаимодействие между слоями контроллер-сервис-репозиторий и у вас получилась очень структурированная работа.
Оставила несколько небольших комментариев, которые помогут немного причесать код. 

И общих комментариев: нужно будет добавить папку target в игнорирование в файл `.gitignore` и удалить из репозитория

2023-03-25 12:17 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FeedService.java
> +            //newFeed = createFeed(methodName, review.getUserId(), review.getReviewId());
Закомментированный код удалён

2023-03-25 12:19 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FilmDbStorageDao.java
> +                        "                    FROM (SELECT likes.film_id FROM likes WHERE user_id = ?) AS f1 " +
Запрос упрощён и выборка обзих фильмов перенесена на уровень service в классе FilmService

2023-03-25 12:25 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/JavaFilmorateApplication.java
> +	//develop git
Комментарий удалён

2023-03-25 12:30 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/DirectorController.java
> +    DirectorService directorService;
Добавлен модификатор private

2023-03-25 12:32 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/DirectorController.java
> +    public DirectorController(DirectorService directorService) {
Добавлена аннотация @AllArgsConstructor ,  @RequiredArgsConstructor необеспечивала создание конструктора с нужной зависимостью

2023-03-25 12:39 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/UserController.java
> +    public UserController(UserService userService, FeedService feedService) {
Добавлена аннотация @RequiredArgsConstructor

2023-03-25 12:40 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/UserController.java
> +    public UserController(UserService userService, FeedService feedService) {
Добавлена аннотация `@ RequiredArgsConstructor`

2023-03-25 12:41 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/DirectorDao.java
Скорректирован code-style

2023-03-25 13:37 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/LikeDao.java
> +        String sql =    "SELECT l.film_id, l.user_id \n" +
Убрал символы переноса из запросов

2023-03-25 13:38 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FriendShipDao.java
поправил code-style

2023-03-25 13:38 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/LikeDao.java
Поправил code-style

2023-03-25 13:43 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/review/ReviewsDaoStandard.java
> +        jdbcTemplate.update(sqlUpdateReviewUseful, review.getUseful() + 1, id);
Добавлена проверка на null

2023-03-25 13:46 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/model/FilmDirector.java
> +    public FilmDirector(long directorId, long filmId) {
Добавлена аннотация `@AllArgsConstructor`

2023-03-25 13:47 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/model/Like.java
> +    public Like(long filmId, long userId) {
Добавлена аннотация @AllArgsConstructor

2023-03-25 13:50 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/service/DirectorService.java
> +@Component
Аннотация изменена на `@Service`

2023-03-26 12:36 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/DirectorController.java
> +    public DirectorController(DirectorService directorService) {
Чтобы аннотация @RequiredArgsConstructor генерира конструктор с нужными полями, поля должны быть помеченый модификатором final:
```@RequiredArgsConstructor позволит получить конструктор с параметром для каждого поля, но эти параметры потребуют специальной обработки. В частности, здесь мы будем работать с неинициализированными полями final, а также с любыми полями, помеченными как @NonNull, которые не инициализируются при объявлении
```

2023-03-26 12:40 UTC, AnastasiyaFomkina requested changes

2023-03-26 12:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/DirectorController.java
> +@AllArgsConstructor
Лучше переписать с помощью `@RequiredArgsConstructor`, так как мы не хотим инжектить все переменные класса. 
Поменяй, пожалуйста, везде, где это возможно `@AllArgsConstructor` на `@RequiredArgsConstructor`

2023-03-26 18:48 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/DirectorController.java
> +@AllArgsConstructor
В ветке с иправлениями не было ошибки 253.
https://github.com/DusynHub/java-filmorate/pull/36

![image](https://user-images.githubusercontent.com/112579759/227797325-f80a233a-3409-47d9-bc95-59239f4b827f.png)

Не понимаю, что вызывает ошибку. Вероятно были изменены файлы тестов со стороны яндекса.

2023-03-27 13:53 UTC, closed without merging