Add friends likes
DusynHub/java-filmorate pull request #7
Opened 2023-02-02 18:29 UTC by DusynHub

Добавлен функционал в соответствии с техническим задание 10-го спринта.

2023-02-03 10:10 UTC, AnastasiyaFomkina requested changes

2023-02-03 10:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/service/UserService.java
> +        for(long idUser : userFriends){
Нужно переписать с помощью [stream api](https://habr.com/ru/company/otus/blog/658999/)
Подсказка: тут отлично подойдет метод `map`

2023-02-03 10:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/service/UserService.java
> +        List<Long> commonFriends = userFriends.stream().filter(friendsFriends::contains).collect(Collectors.toList());
Стримы принято бить по методам, чтобы их было проще читать:
```suggestion
        List<Long> commonFriends = userFriends.stream()
            .filter(friendsFriends::contains)
            .collect(Collectors.toList());
```

Поправь, пожалуйста, по всему проекту

2023-02-03 10:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/service/UserService.java
> +    public UserStorage getUserStorage() {
Метод нигде не используется, нужно удалить

2023-02-03 10:10 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/javafilmorate/controllers/FilmControllerTest.java
> +        assertEquals(400, response.statusCode());
Скорее всего если удалишь ручную валидацию, сломаются тесты. Спринговую валидацию можно проверять с помощью фарбики. Почитать можно [вот тут](https://reflectoring.io/bean-validation-with-spring-boot/#:~:text=%3B%0A%20%20%0A%20%20//%20...%0A%0A%7D-,Validating%20Programmatically,-There%20may%20be)

2023-02-04 14:27 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
>          if (StringValidator.isLengthBiggerThanMaxLength(film.getDescription(), MAX_DESCRIPTION_LENGTH)) {
Исключил валидацию при помощи методов, кроме проверки на отсутвие имени и использования логина при отсутствии имени. 

Все проверки при помощи кастомных аннотаций.

2023-02-04 14:27 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
>          if (LocalDateValidator.isDateTooOld(film.getReleaseDate(), THE_OLDEST_RELEASE_DATE)) {
Исключил валидацию при помощи методов, кроме проверки на отсутвие имени и использования логина при отсутствии имени. 

Все проверки при помощи кастомных аннотаций.

2023-02-04 14:27 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
>          if (DurationValidator.isDurationNegativeOrZero(film.getDuration())) {
Исключил валидацию при помощи методов, кроме проверки на отсутвие имени и использования логина при отсутствии имени. 

Все проверки при помощи кастомных аннотаций.

2023-02-04 14:27 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
>          if (StringValidator.isNullOrEmpty(film.getName())) {
Исключил валидацию при помощи методов, кроме проверки на отсутвие имени и использования логина при отсутствии имени. 

Все проверки при помощи кастомных аннотаций.

2023-02-04 14:27 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +    private final FilmStorage filmStorage;
Удалил неиспользуемый метод

2023-02-04 14:27 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +    public FilmStorage getFilmStorage() {
Удалил неиспользуемый метод

2023-02-04 14:28 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/UserController.java
> +    private void validateUser(User user) {
Все проверки вынес в кастомные аннотации. 

Правильно ли реализован метод по вызову фабрики валидаторов и валидатора  и их тестирование?

2023-02-04 14:29 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/exceptions/ErrorResponse.java
> +    private final Optional<String> error;
Изменил `Optional `на `String`

2023-02-04 14:29 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/exceptions/ExceptionHandler.java
> +public class ExceptionHandler {
Изменил название класса

2023-02-04 14:30 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/exceptions/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler
Благодарю за подробные замечания по проекту и здесь в частности. 
Спасибо за тщательное ревью)
Долго голову ломал, почему тут полное название необходимо.

2023-02-04 14:31 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +    public FilmStorage getFilmStorage() {
Удалил неиспользуемый метод

2023-02-04 14:31 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/service/UserService.java
> +        for(long idUser : userFriends){
Переписал с использованием stream api
Сразу не подумал о map. Так действительно лучше выглядит.

2023-02-04 14:32 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/service/UserService.java
> +        for(long idUser : commonFriends){
Переписал с использование `stream api`

2023-02-04 14:32 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/service/UserService.java
> +        List<Long> commonFriends = userFriends.stream().filter(friendsFriends::contains).collect(Collectors.toList());
Поправил разбиение стримов

2023-02-04 14:33 UTC, DusynHub commented on src/test/java/ru/yandex/practicum/javafilmorate/controllers/FilmControllerTest.java
> +        assertEquals(400, response.statusCode());
Удалил все ручные валидации. Оставил только кастомные аннотации. Не уверен в корректности тестов аннотаций для валидации.

2023-02-05 12:16 UTC, AnastasiyaFomkina requested changes
C тестами валидации все отлично, правильно понял концепцию, молодец 👍

2023-02-05 12:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/javafilmorate/controllers/FilmControllerTest.java
> +    static void afterAll() {
_Опционально_
В тестах лучше отказаться от статических `@BeforeAll` и `@AfterAll`, лучше использовать `@BeforeEach` и `@AfterEach`, чтобы контекст тестов всегда был чистым и ничего не перетиралось.

В целом лучше стараться избегать статики, если это возможно, так как он не соответствует парадигме ооп и делает код менее безопасным

2023-02-05 12:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/javafilmorate/controllers/UserControllerTest.java
>          app.close();
Лучше удалить ручное поднятие и закрытие контекста , так как аннотация `@SpringBootTest` делает это автоматически. Единственный момент - она не знает на каком порту у нас поднимается сервер, поэтому нужно прописать его в параметрах аннотации:
`@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)`.
Поправь, пожалуйста, и для теста контроллера фильмов

2023-02-05 12:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/javafilmorate/service/ValidatingServiceForTestingTest.java
> +class ValidatingServiceForTestingTest {
🔥

2023-02-05 12:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/javafilmorate/service/ValidatingServiceForTestingTest.java
> +@RequiredArgsConstructor
Лишняя аннотация, так как класс `ValidatingServiceForTesting` инжектится с помощью `@Autowired`

2023-02-05 12:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/javafilmorate/service/ValidatingServiceForTestingTest.java
> +@ExtendWith(SpringExtension.class)
Уже есть внутри `@SpringBootTest`, поэтому лучше удалить

2023-02-05 12:16 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/javafilmorate/service/ValidatingServiceForTestingTest.java
> +        String tooLongDescription = "Test description Test description Test description" +
Лучше нагенерить длинное описание, чем вбивать его вручную. Чуть выше оставила ссылку на статью, где описано, как это можно сделать

2023-02-05 12:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/util/DurationPositiveOrZero.java
> +public @interface DurationPositiveOrZero {
Если уже есть готовые валидации, лучше использовать их, а кастомные создавать только в тех случаях, под которые не подходят стандартные, например, как с датой создания фильмов

2023-02-05 12:16 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/util/DurationPositiveOrZero.java
> +public @interface DurationPositiveOrZero {
[@PositiveOrZero](https://www.baeldung.com/javax-validation#:~:text=%40Positive%20and-,%40PositiveOrZero,-apply%20to%20numeric)

2023-02-05 16:44 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +    private void checkFilmExistence(long id) {
Благодарю за комментарии. Ура много замечаний) Люблю, когда много замечаний во время обучения. Пока исправляешь много нового узнаешь.

Перенёс все проверки в классы сервисы.

2023-02-05 16:45 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/service/ValidatingServiceForTesting.java
> +public class ValidatingServiceForTesting {
Перенёс в тесты. Думал, что проверяемый класс всегда должен быть в src, а тест его в test.

2023-02-05 16:47 UTC, DusynHub commented on src/test/java/ru/yandex/practicum/javafilmorate/controllers/FilmControllerTest.java
> +    static void afterAll() {
Использовал предлагаемый метод генератор.

А если удобно использовать один и тот же набор объектов, то всё равно @BeforeAll лучше не использовать?
В таком случае лучше сделать пачку полей private final с нужными объектами?

Убрал в тестах @BeforeAll и @AfterAll

2023-02-05 16:47 UTC, DusynHub commented on src/test/java/ru/yandex/practicum/javafilmorate/controllers/UserControllerTest.java
>          app.close();
Убрал ручное поднятие. Не знал как запустить без, а параметры аннотации помогли)

2023-02-05 16:48 UTC, DusynHub commented on src/test/java/ru/yandex/practicum/javafilmorate/service/ValidatingServiceForTestingTest.java
> +@RequiredArgsConstructor
Убрал @ExtendWith(SpringExtension.class)

2023-02-05 16:48 UTC, DusynHub commented on src/test/java/ru/yandex/practicum/javafilmorate/service/ValidatingServiceForTestingTest.java
> +        String tooLongDescription = "Test description Test description Test description" +
Использовал метод генератор из предлагаемой выше ссылки. Благодарю за ссылки к замечаниям, очень удобно.

2023-02-05 16:49 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/util/DurationPositiveOrZero.java
> +public @interface DurationPositiveOrZero {
Аннотация @PositiveOrZero применяется только к:
"BigDecimal
BigInteger
byte, short, int, long, float, double and their respective wrappers".

Использовал для длительности переменную типа Duration. Именно поэтому делла кастомную валидацию. Это считается случаем, когда стандартные не подходят или можно как-то адаптировать стандартную аннотацию? 

Не смог найти удовлетворяющего решения по адаптации аннотации @PositiveOrZero  к проверке поля типа Duration.

2023-02-06 08:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/util/DurationPositiveOrZero.java
> +public @interface DurationPositiveOrZero {
А, точно, как то ускользноло от моего внимания, что ты применяешь `Duration`, а не `Long` для замера продолжительности времени. Тогда все верно, аннотация _@PositiveOrZero_ не подходит. Клево, что разобрался и написал кастомную 🔥

2023-02-06 09:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/javafilmorate/controllers/FilmControllerTest.java
> +    static void afterAll() {
Да, если нужен один и тот же пул объектов для всех тестов, удобнее сразу их инициализировать, как переменные класса, можно их сделать как `private final`, если они никак не будут изменяться в тестах, или просто `private`.
`@BeforeAll` и `@AfterAll` используются только в специфических случаях, когда нам нужно инициализировать одинаковый контекст для всех тестов и не очищать его каждый раз. Но честно, за всю мою практику, я пока с такими случаями не встречалась. Так как мы стараемся проверять, как ведет себя тот или иной метод в вакууме, обычно контекст, когда он нужен инициализируется перед тестом, а потом сразу после него закрывается, чтобы данные из других тестов никак не смогли повлиять на результат выполнения. А все уже сложные тесты с интеграциями пишутся тестировщиками, которые составляют сложные use-кэйсы по всему процессу

2023-02-06 09:50 UTC, AnastasiyaFomkina approved these changes

2023-02-06 12:19 UTC, merged