Add database
DusynHub/java-filmorate pull request #9
Opened 2023-03-02 23:15 UTC by DusynHub

Homework Sprint 11. Version 1.01

2023-03-03 15:31 UTC, AnastasiyaFomkina requested changes

2023-03-03 15:31 UTC, AnastasiyaFomkina commented on pom.xml
> +<!--			<artifactId>spring-boot-starter-data-jpa</artifactId>-->
Пока не используем, лучше удалить

2023-03-03 15:31 UTC, AnastasiyaFomkina commented on pom.xml
> +<!--			<artifactId>jackson-datatype-jsr310</artifactId>-->
Лучше тоже удалить, а не комментировать

2023-03-03 15:31 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/GenreController.java
> +    public GenreController(GenreService genreService) {
_Саморазвитие_
Чтобы максимально избавится от однотипного кода, очень удобно использовать [@RequiredArgsConstructor ](https://www.baeldung.com/spring-injection-lombok#:~:text=Constructor%20Injection%20With%20Lombok) из библиотеки `lombok`. Он автоматически заинжектит все нужные нам поля

2023-03-03 15:31 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FilmDbStorageDao.java
> +        return null;
Нужно дописать метод

2023-03-03 15:31 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FilmDbStorageDao.java
> +                                                "       SELECT film_id, COUNT(film_id) as count_likes\n" +
Нужно избавиться от вложенных подзапросов

2023-03-03 15:31 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FilmGenreDao.java
> +        ArrayList<Genre> genres = new ArrayList(new HashSet<>(film.getGenres()));
Точно ли нужно приводить список к сету, а потом снова к списку?

2023-03-03 15:31 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/MpaDao.java
> +        try{    Mpa mpa = jdbcTemplate.queryForObject(sql,
Слишком много отступов после скобочки, нужно поправить класс по `code-style`. Это просто сделать если воспользоваться сочетанием клавиш в `IDEA` [Ctrl+Alt+L](https://www.jetbrains.com/idea/guide/tips/reformat-file/)

2023-03-03 15:31 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/MpaDao.java
> +                log.info("Найден MPA-рейтинг: c id = {} названием = {}", mpa.getId(), mpa.getName());
Прежде, чем получить ` .getId()`, нужно проверить, что `mpa !=null`

2023-03-03 23:43 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/MpaDao.java
> +                log.info("Найден MPA-рейтинг: c id = {} названием = {}", mpa.getId(), mpa.getName());
Я так понял, что исключение EmptyResultDataAccessException будет выброшено при использовании queryForObject, если будет возращено null.

Исключение перехватываю и выбрасываю своё.

  } catch(EmptyResultDataAccessException e){
            log.debug("MPA-рейтинг с идентификатором {} не найден.", id);
            throw new EntityDoesNotExistException(String.format(
                                                "MPA с идентификатором %d не найден.", id));
        }

Всё равно нужна дополнительная проверка? Проверку добавил, просто хочу понимать её обязательность.

2023-03-03 23:44 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FilmGenreDao.java
> +        ArrayList<Genre> genres = new ArrayList(new HashSet<>(film.getGenres()));
Испавил. Для оставления уникальных жанров использую метод distinct() Stream API. Не подумал, что есть готовый метод.

2023-03-03 23:45 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FilmDbStorageDao.java
> +                                                "       SELECT film_id, COUNT(film_id) as count_likes\n" +
Для облегчения запроса изменил схему БД и добавил для фильма поле likes_amount. Правда при добавлении и удалении лайка теперь два запроса в БД на добавление в таблицу likes и на обновление атрибута likes_amount в таблице films.

2023-03-03 23:48 UTC, DusynHub commented on pom.xml
> +<!--			<artifactId>jackson-datatype-jsr310</artifactId>-->
Удалил.

2023-03-03 23:48 UTC, DusynHub commented on pom.xml
> +<!--			<artifactId>spring-boot-starter-data-jpa</artifactId>-->
Добрый день, Анасасия!
Благодарю Вас за то, что нашли на проведение ревью в пятницу. Прощу прощения, что затянул. Наверное все полно таких "опоздунов", отложивших на последний момент.

Совсем забыл проверить POM файл. Моя беда.

2023-03-03 23:48 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/GenreController.java
> +    public GenreController(GenreService genreService) {
Добавил в классы моделей и где не нужена аннотация @Qualifier

2023-03-03 23:49 UTC, DusynHub commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FilmDbStorageDao.java
> +        return null;
Дописал в этом классе и классе UserDbStorageDao

2023-03-05 07:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FilmDbStorageDao.java
> +                                                "       SELECT film_id, COUNT(film_id) as count_likes\n" +
Иногда лучше два маленьких запроса, чем один тяжелый 👍

2023-03-05 07:31 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/MpaDao.java
> +                log.info("Найден MPA-рейтинг: c id = {} названием = {}", mpa.getId(), mpa.getName());
Ну тут не совсем так, в [документации](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/dao/EmptyResultDataAccessException.html) указано, что данная ошибка возвращается в том случае, если `queryForObject` вернул одну строку(элемент) или ноль. В некоторых случаях `null` может считаться элементом, поэтому важно проверить, что когда мы получаем `id`, полученный `элемент != null`

2023-03-05 07:38 UTC, AnastasiyaFomkina approved these changes

2023-03-05 19:06 UTC, merged